"""add group cohort, drop invite link cohort

Revision ID: 091c9af478ba
Revises: 47a10a637317
Create Date: 2026-07-25 08:15:29.379059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091c9af478ba'
down_revision: Union[str, None] = '47a10a637317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('cohort', sa.String(length=100), nullable=True))
    op.drop_column('invite_links', 'cohort')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('cohort', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('groups', 'cohort')
    # ### end Alembic commands ###
