"""phase 3: monnify invoice fields, contribution events, webhook events

Revision ID: 0abce8cff563
Revises: cd291a52ef86
Create Date: 2026-07-22 15:27:34.079199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '0abce8cff563'
down_revision: Union[str, None] = 'cd291a52ef86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=True)
    op.create_table('contribution_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contribution_id', sa.UUID(), nullable=False),
    sa.Column('from_status', PGEnum('pending', 'paid', 'expired', 'flagged_for_review', 'paid_manual', name='contribution_status', create_type=False), nullable=False),
    sa.Column('to_status', PGEnum('pending', 'paid', 'expired', 'flagged_for_review', 'paid_manual', name='contribution_status', create_type=False), nullable=False),
    sa.Column('actor_type', sa.Enum('webhook', 'reconciliation_job', 'rep_manual', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_events_contribution_id'), 'contribution_events', ['contribution_id'], unique=False)
    op.add_column('contributions', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('contributions', sa.Column('invoice_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'invoice_expires_at')
    op.drop_column('contributions', 'bank_name')
    op.drop_index(op.f('ix_contribution_events_contribution_id'), table_name='contribution_events')
    op.drop_table('contribution_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
    sa.Enum(name='actor_type').drop(op.get_bind(), checkfirst=True)
