"""phase 2: split user names, purses and contributions

Revision ID: 16d37abd5980
Revises: a74e880d4c01
Create Date: 2026-07-22 14:24:32.171429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d37abd5980'
down_revision: Union[str, None] = 'a74e880d4c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('cohort', sa.String(length=100), nullable=True),
    sa.Column('created_by_group_admin_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enroll_mode', sa.Enum('snapshot', 'auto_enroll', name='enroll_mode'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'archived', name='purse_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_group_admin_id'], ['group_admins.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purses_created_by_group_admin_id'), 'purses', ['created_by_group_admin_id'], unique=False)
    op.create_index(op.f('ix_purses_group_id'), 'purses', ['group_id'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purse_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('amount_expected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'expired', 'flagged_for_review', 'paid_manual', name='contribution_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['purse_id'], ['purses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purse_id', 'member_id', name='uq_contribution_purse_member')
    )
    op.create_index(op.f('ix_contributions_member_id'), 'contributions', ['member_id'], unique=False)
    op.create_index(op.f('ix_contributions_purse_id'), 'contributions', ['purse_id'], unique=False)
    op.drop_column('members', 'name')

    # Add nullable, backfill, then tighten to NOT NULL -- safe against any
    # pre-existing rows rather than assuming the table is empty.
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.execute("UPDATE users SET first_name = '', last_name = '' WHERE first_name IS NULL")
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('members', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_contributions_purse_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_member_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_purses_group_id'), table_name='purses')
    op.drop_index(op.f('ix_purses_created_by_group_admin_id'), table_name='purses')
    op.drop_table('purses')
    # ### end Alembic commands ###
    sa.Enum(name='contribution_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='purse_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='enroll_mode').drop(op.get_bind(), checkfirst=True)
