"""phase 6 payout allocations

Revision ID: 4dbe1e49a6c7
Revises: 74c9cfaae50b
Create Date: 2026-07-22 17:21:41.374364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbe1e49a6c7'
down_revision: Union[str, None] = '74c9cfaae50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('purse_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.ForeignKeyConstraint(['purse_id'], ['purses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_allocations_payout_id'), 'payout_allocations', ['payout_id'], unique=False)
    op.create_index(op.f('ix_payout_allocations_purse_id'), 'payout_allocations', ['purse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_allocations_purse_id'), table_name='payout_allocations')
    op.drop_index(op.f('ix_payout_allocations_payout_id'), table_name='payout_allocations')
    op.drop_table('payout_allocations')
    # ### end Alembic commands ###
