"""phase 5: settlement accounts, payouts, payout events

Revision ID: 74c9cfaae50b
Revises: 0abce8cff563
Create Date: 2026-07-22 16:39:23.487392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = '74c9cfaae50b'
down_revision: Union[str, None] = '0abce8cff563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_group_admin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_group_admin_id'], ['group_admins.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_accounts_group_id'), 'settlement_accounts', ['group_id'], unique=True)
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('purse_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'processing', 'completed', 'failed', 'rejected', name='payout_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('monnify_transfer_ref', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['purse_id'], ['purses.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['group_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_group_id'), 'payouts', ['group_id'], unique=False)
    op.create_index(op.f('ix_payouts_purse_id'), 'payouts', ['purse_id'], unique=False)
    op.create_table('payout_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('from_status', PGEnum('requested', 'approved', 'processing', 'completed', 'failed', 'rejected', name='payout_status', create_type=False), nullable=False),
    sa.Column('to_status', PGEnum('requested', 'approved', 'processing', 'completed', 'failed', 'rejected', name='payout_status', create_type=False), nullable=False),
    sa.Column('actor_type', sa.Enum('group_admin', 'platform_admin', 'webhook', name='payout_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_events_payout_id'), 'payout_events', ['payout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_events_payout_id'), table_name='payout_events')
    op.drop_table('payout_events')
    op.drop_index(op.f('ix_payouts_purse_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_group_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_settlement_accounts_group_id'), table_name='settlement_accounts')
    op.drop_table('settlement_accounts')
    # ### end Alembic commands ###
    sa.Enum(name='payout_actor_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payout_status').drop(op.get_bind(), checkfirst=True)
