"""phase 6 audit log and permission locks

Revision ID: 83d4db43c592
Revises: 4dbe1e49a6c7
Create Date: 2026-07-22 17:37:17.228254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '83d4db43c592'
down_revision: Union[str, None] = '4dbe1e49a6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

APP_ROLE = settings.APP_DB_ROLE
APP_ROLE_PASSWORD = settings.APP_DB_PASSWORD


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('group_admin', 'platform_admin', 'member', 'webhook', 'reconciliation_job', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    # ### end Alembic commands ###

    # Seed the single chain-head row AuditService.record_event() locks on.
    op.execute("INSERT INTO audit_chain_head (id, last_row_hash) VALUES (1, NULL)")

    # Create the restricted, non-superuser role the running application
    # actually connects as (see app/core/db.py + settings.RUNTIME_DATABASE_URL).
    # This is what makes the REVOKE below a real enforcement point rather
    # than a no-op: a superuser connection bypasses table ACLs entirely, so
    # if the app queried as the migration's own (superuser) role, revoking
    # UPDATE/DELETE here would have no effect on it.
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                CREATE ROLE {APP_ROLE} LOGIN PASSWORD '{APP_ROLE_PASSWORD}';
            END IF;
        END
        $$;
        """
    )
    op.execute(f"GRANT CONNECT ON DATABASE {op.get_bind().engine.url.database} TO {APP_ROLE}")
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {APP_ROLE}")
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}")
    op.execute(
        f"ALTER DEFAULT PRIVILEGES FOR ROLE {op.get_bind().engine.url.username} IN SCHEMA public "
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {APP_ROLE}"
    )

    # The non-negotiable rule from implementation-guide.md Section 9: audit
    # tables can be written and read, never edited or deleted -- not by a
    # rep, not by an admin, not by a bug. Applies to the universal AuditLog
    # table and the domain-specific event tables it generalizes.
    for audit_table in ("audit_log", "contribution_events", "payout_events"):
        op.execute(f"REVOKE UPDATE, DELETE ON {audit_table} FROM {APP_ROLE}")


def downgrade() -> None:
    op.execute(f"GRANT UPDATE, DELETE ON contribution_events, payout_events TO {APP_ROLE}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('audit_chain_head')
    # ### end Alembic commands ###
