"""add monnify settlement logs table

Revision ID: 89604a1e5448
Revises: f3a8c2d19b4e
Create Date: 2026-07-28 17:16:30.761431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89604a1e5448'
down_revision: Union[str, None] = 'f3a8c2d19b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monnify_settlement_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_reference', sa.String(length=100), nullable=False),
    sa.Column('sub_account_code', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('settled_amount', sa.Float(), nullable=False),
    sa.Column('destination_account_name', sa.String(length=150), nullable=True),
    sa.Column('destination_account_number', sa.String(length=20), nullable=True),
    sa.Column('destination_bank_code', sa.String(length=10), nullable=True),
    sa.Column('destination_bank_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settlement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monnify_settlement_logs_group_id'), 'monnify_settlement_logs', ['group_id'], unique=False)
    op.create_index(op.f('ix_monnify_settlement_logs_settlement_reference'), 'monnify_settlement_logs', ['settlement_reference'], unique=True)
    op.create_index(op.f('ix_monnify_settlement_logs_sub_account_code'), 'monnify_settlement_logs', ['sub_account_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monnify_settlement_logs_sub_account_code'), table_name='monnify_settlement_logs')
    op.drop_index(op.f('ix_monnify_settlement_logs_settlement_reference'), table_name='monnify_settlement_logs')
    op.drop_index(op.f('ix_monnify_settlement_logs_group_id'), table_name='monnify_settlement_logs')
    op.drop_table('monnify_settlement_logs')
    # ### end Alembic commands ###
