"""phase 7 notifications

Revision ID: a022f9b521ad
Revises: 83d4db43c592
Create Date: 2026-07-22 18:32:48.745629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a022f9b521ad'
down_revision: Union[str, None] = '83d4db43c592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_to_email'), 'notification_logs', ['to_email'], unique=False)
    op.add_column('purses', sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purses', 'last_reminder_sent_at')
    op.drop_index(op.f('ix_notification_logs_to_email'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###

    sa.Enum(name='notification_status').drop(op.get_bind(), checkfirst=True)
