"""add FK constraint on invite_links.purse_id now that purses exists

Revision ID: cd291a52ef86
Revises: 16d37abd5980
Create Date: 2026-07-22 14:42:46.298796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd291a52ef86'
down_revision: Union[str, None] = '16d37abd5980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_invite_links_purse_id_purses", "invite_links", "purses", ["purse_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_invite_links_purse_id_purses", "invite_links", type_="foreignkey")
    # ### end Alembic commands ###
