"""member can belong to multiple groups

Revision ID: cf671bb40c89
Revises: a022f9b521ad
Create Date: 2026-07-23 08:13:32.543736

members.user_id previously had a bare unique index, meaning one User could
only ever have one Member row, platform-wide, across every group. That
made it impossible for an existing member (or a group_admin) to also join
a second group as a member -- POST /members/join/{token} unconditionally
409'd. This replaces the bare unique index with a non-unique index plus a
composite unique constraint on (user_id, group_id): a user still can't
join the *same* group twice, but can now hold Member rows in multiple
groups. See MemberService.join_additional_group and the new
POST /members/join-additional/{token} endpoint.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf671bb40c89'
down_revision: Union[str, None] = 'a022f9b521ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_members_user_id', table_name='members')
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.create_unique_constraint('uq_members_user_id_group_id', 'members', ['user_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_members_user_id_group_id', 'members', type_='unique')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.create_index('ix_members_user_id', 'members', ['user_id'], unique=True)
    # ### end Alembic commands ###
